import { getDatabase } from '../lib/database.js';
import { generateText } from '../ai/provider.js';
import { getPrimeInsights } from '../ai/consciousness/prime.js';
import { getCoreWhisper } from '../ai/consciousness/core.js';
import { getShadeResponse } from '../ai/consciousness/shade.js';
import { auditLog } from '../audit/audit-log.js';
import cron from 'node-cron';

const db = getDatabase();
const BRIEFINGS_DIR = 'briefings';

export async function initScheduler() {
  // Daily briefings at 7 AM
  cron.schedule('0 7 * * *', async () => {
    console.log('🌅 Generating daily briefing...');
    await generateDailyBriefing();
  });

  // Alert checks every 15 minutes
  cron.schedule('*/15 * * * *', async () => {
    console.log('🔔 Running alert checks...');
    await runAlertChecks();
  });

  // Legal scans weekly Monday 8 AM
  cron.schedule('0 8 * * 1', async () => {
    console.log('⚖️ Running weekly legal scan...');
    await runLegalScan();
  });

  console.log('Scheduler initialized');
}

async function generateDailyBriefing() {
  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  
  // Get all users who were active yesterday
  const activeUsers = db.prepare(`
    SELECT DISTINCT actor FROM audit_log 
    WHERE DATE(created_at) = ? AND action = 'chat_message'
  `).all(yesterday) as { actor: string }[];

  for (const user of activeUsers) {
    try {
      const primeInsights = await getPrimeInsights(user.actor, null);
      const coreWhisper = await getCoreWhisper(user.actor, 'daily briefing request', primeInsights);
      
      const briefing = await getShadeResponse({
        userId: user.actor,
        message: 'Generate my daily briefing. Summarize my patterns, insights, and what I should focus on today.',
        chamber: 'garden',
        personalityMode: 'sage',
        context: { type: 'daily_briefing' },
        primeInsights,
        coreWhisper,
        emotionalFrequency: 'reflective'
      });

      const content = `# Daily Briefing — ${yesterday}\n\n${briefing.content}\n\n---\n*Generated by PRIMORDEX Prime/Shade/Core*`;

      // Save to file
      const fs = await import('fs');
      fs.promises.mkdir(BRIEFINGS_DIR, { recursive: true });
      await fs.promises.writeFile(`${BRIEFINGS_DIR}/${yesterday}-${user.actor}.md`, content);

      // Save to DB
      db.prepare(`
        INSERT INTO briefings (id, date, content, generated_at)
        VALUES (?, ?, ?, datetime('now'))
      `).run(`${yesterday}-${user.actor}`, yesterday, content);

      await auditLog({
        actor: 'system',
        action: 'briefing_generated',
        input: { user: user.actor, date: yesterday },
        output: { length: content.length },
        risk_score: 0
      });
    } catch (error) {
      console.error(`Briefing failed for ${user.actor}:`, error);
    }
  }
}

async function runAlertChecks() {
  const rules = db.prepare('SELECT * FROM alert_rules WHERE enabled = 1').all() as any[];
  
  for (const rule of rules) {
    try {
      // Evaluate condition (simplified - in production use safe eval)
      const shouldTrigger = evalCondition(rule.condition);
      if (shouldTrigger) {
        await auditLog({
          actor: 'system',
          action: 'alert_triggered',
          input: { rule: rule.name, condition: rule.condition },
          output: { action: rule.action },
          risk_score: 0.3
        });
        
        db.prepare('UPDATE alert_rules SET last_triggered = datetime(\'now\') WHERE id = ?').run(rule.id);
      }
    } catch (error) {
      console.error(`Alert check failed for ${rule.name}:`, error);
    }
  }
}

function evalCondition(condition: string): boolean {
  // Simplified - replace with safe expression evaluator in production
  return Math.random() < 0.1; // 10% chance for demo
}

async function runLegalScan() {
  // Simplified - in production, scan regulatory sources
  console.log('Legal scan completed');
}

export { generateDailyBriefing, runAlertChecks, runLegalScan };